spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: provider-admin
  zipkin:
    base-url: http://10.3.50.121:9411

server:
  port: 11000

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/