spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: provider-payment
  zipkin:
    base-url: http://192.168.141.204:9411
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.141.206:3306/myshop_1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    cluster:
      nodes: 192.168.141.206:6379,192.168.141.206:6380,192.168.141.206:6381
    lettuce:
      # 连接池配置
      pool:
        # 连接池中的最小空闲连接，默认 0
        min-idle: 0
        # 连接池中的最大空闲连接，默认 8
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制），默认 -1ms
        max-wait: -1ms
        # 连接池最大连接数（使用负值表示没有限制），默认 8
        max-active: 8
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.141.206:9876
        bindings:
          MessageTopic: {consumer.orderly: true}
      bindings:
        # consumer.maxAttempts
        # 消息最大可以被尝试消费的次数，包含第一次投递
        # 设为 1，表示不重试，注意该值必须大于 0
        MessageTopic: {destination: MessageTopic, content-type: text/plain, group: MessageGroup, consumer.maxAttempts: 1}

server:
  port: 11020

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

mybatis:
  configuration:
    cache-enabled: true
  type-aliases-package: com.funtl.hello.spring.cloud.provider.domain
  mapper-locations: classpath:mapper/*.xml
