spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-zuul-business
  zipkin:
    base-url: http://192.168.141.204:9411

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

zuul:
  routes:
    api-business-admin:
      path: /api/business/admin/**
      serviceId: business-admin