spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: business-admin
  zipkin:
    base-url: http://10.3.50.121:9411
  cloud:
    config:
      uri: http://localhost:8888
      name: config-client
      label: master
      profile: dev

server:
  port: 12000

feign:
  hystrix:
    enabled: true

eureka:
  instance:
    hostname: localhost
    metadata-map:
      cluster: business
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"