spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: addons-message-rocketmq
  zipkin:
    base-url: http://192.168.141.204:9411
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.141.206:9876
      bindings:
        MessageTopic: {destination: MessageTopic, content-type: application/json}

server:
  port: 13000

eureka:
  instance:
    hostname: localhost
    metadata-map:
      cluster: message
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"